//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hys.CareRIS.Application.AuditService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DataResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool isSuccessfulField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string risDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string systemDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string errorCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool isSuccessful {
            get {
                return this.isSuccessfulField;
            }
            set {
                if ((this.isSuccessfulField.Equals(value) != true)) {
                    this.isSuccessfulField = value;
                    this.RaisePropertyChanged("isSuccessful");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string risData {
            get {
                return this.risDataField;
            }
            set {
                if ((object.ReferenceEquals(this.risDataField, value) != true)) {
                    this.risDataField = value;
                    this.RaisePropertyChanged("risData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string systemData {
            get {
                return this.systemDataField;
            }
            set {
                if ((object.ReferenceEquals(this.systemDataField, value) != true)) {
                    this.systemDataField = value;
                    this.RaisePropertyChanged("systemData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.errorCodeField, value) != true)) {
                    this.errorCodeField = value;
                    this.RaisePropertyChanged("errorCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuditService.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name devID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRisLicense", ReplyAction="*")]
        Hys.CareRIS.Application.AuditService.GetRisLicenseResponse GetRisLicense(Hys.CareRIS.Application.AuditService.GetRisLicenseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRisLicense", ReplyAction="*")]
        System.Threading.Tasks.Task<Hys.CareRIS.Application.AuditService.GetRisLicenseResponse> GetRisLicenseAsync(Hys.CareRIS.Application.AuditService.GetRisLicenseRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRisLicenseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRisLicense", Namespace="http://tempuri.org/", Order=0)]
        public Hys.CareRIS.Application.AuditService.GetRisLicenseRequestBody Body;
        
        public GetRisLicenseRequest() {
        }
        
        public GetRisLicenseRequest(Hys.CareRIS.Application.AuditService.GetRisLicenseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRisLicenseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string devID;
        
        public GetRisLicenseRequestBody() {
        }
        
        public GetRisLicenseRequestBody(string devID) {
            this.devID = devID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRisLicenseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRisLicenseResponse", Namespace="http://tempuri.org/", Order=0)]
        public Hys.CareRIS.Application.AuditService.GetRisLicenseResponseBody Body;
        
        public GetRisLicenseResponse() {
        }
        
        public GetRisLicenseResponse(Hys.CareRIS.Application.AuditService.GetRisLicenseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRisLicenseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Hys.CareRIS.Application.AuditService.DataResult GetRisLicenseResult;
        
        public GetRisLicenseResponseBody() {
        }
        
        public GetRisLicenseResponseBody(Hys.CareRIS.Application.AuditService.DataResult GetRisLicenseResult) {
            this.GetRisLicenseResult = GetRisLicenseResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : Hys.CareRIS.Application.AuditService.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<Hys.CareRIS.Application.AuditService.ServiceSoap>, Hys.CareRIS.Application.AuditService.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Hys.CareRIS.Application.AuditService.GetRisLicenseResponse Hys.CareRIS.Application.AuditService.ServiceSoap.GetRisLicense(Hys.CareRIS.Application.AuditService.GetRisLicenseRequest request) {
            return base.Channel.GetRisLicense(request);
        }
        
        public Hys.CareRIS.Application.AuditService.DataResult GetRisLicense(string devID) {
            Hys.CareRIS.Application.AuditService.GetRisLicenseRequest inValue = new Hys.CareRIS.Application.AuditService.GetRisLicenseRequest();
            inValue.Body = new Hys.CareRIS.Application.AuditService.GetRisLicenseRequestBody();
            inValue.Body.devID = devID;
            Hys.CareRIS.Application.AuditService.GetRisLicenseResponse retVal = ((Hys.CareRIS.Application.AuditService.ServiceSoap)(this)).GetRisLicense(inValue);
            return retVal.Body.GetRisLicenseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Hys.CareRIS.Application.AuditService.GetRisLicenseResponse> Hys.CareRIS.Application.AuditService.ServiceSoap.GetRisLicenseAsync(Hys.CareRIS.Application.AuditService.GetRisLicenseRequest request) {
            return base.Channel.GetRisLicenseAsync(request);
        }
        
        public System.Threading.Tasks.Task<Hys.CareRIS.Application.AuditService.GetRisLicenseResponse> GetRisLicenseAsync(string devID) {
            Hys.CareRIS.Application.AuditService.GetRisLicenseRequest inValue = new Hys.CareRIS.Application.AuditService.GetRisLicenseRequest();
            inValue.Body = new Hys.CareRIS.Application.AuditService.GetRisLicenseRequestBody();
            inValue.Body.devID = devID;
            return ((Hys.CareRIS.Application.AuditService.ServiceSoap)(this)).GetRisLicenseAsync(inValue);
        }
    }
}
