using System;

namespace Hys.CareRIS.Application.Dtos.Report
{
    public enum LockType
    {
        Booking = 1,
        Register = 2,
        Report = 3,
        QC = 4
    }

    public enum DictionaryTag
    {
        Gender = 1,
        Department = 2,
        InhospitalRegion = 3,
        FilmSpec = 4,
        PatientType = 5,
        AgeUnit = 6,
        JobTitle = 7,
        ApplyDoctor = 8,
        Marriage = 9,
        ErethismCode = 10,
        ErethismGrade = 11,
        BodyCategory = 12,
        RPStatus = 13,
        PrintTemplateType = 14,
        BookingDuration1 = 15,
        FileType = 16,
        AccordRate = 17,
        BookingDuration2 = 18,
        ReportQuality = 19,
        Positive = 21,
        ChargeType = 52,
        Observation = 65,
        Inspection = 66,
        YesNo = 70,
        ContrastName = 80,
        Priority = 115,
        ReportExternalURL = 116,
        DisqualifyImageNotifyIP = 121
    }

    public enum RPStatus
    {
        Unknown = 0,
        NoCheck = 10,
        CheckIn = 20,
        Repeatshot = 25,
        Examing = 30,
        RPCancel = 40,
        Examination = 50,
        Draft = 100,
        Reject = 105,
        Submit = 110,
        FirstApprove = 120,
        SecondApprove = 130
    }

    public class ReportCommon
    {
        public const string FIELDNAME_PATIENTID = "tbRegPatient__PatientID";
        public const string FIELDNAME_LOCALNAME = "tbRegPatient__LocalName";

        public const string FIELDNAME_ORDERGUID = "tbRegOrder__OrderGuid";
        public const string FIELDNAME_ACCNO = "tbRegOrder__AccNO";

        public const string FIELDNAME_tbRegPatient__Address = "TBREGPATIENT__ADDRESS";
        public const string FIELDNAME_tbRegPatient__Alias = "TBREGPATIENT__ALIAS";
        public const string FIELDNAME_tbRegPatient__Birthday = "TBREGPATIENT__BIRTHDAY";
        public const string FIELDNAME_tbRegPatient__Comments = "TBREGPATIENT__COMMENTS";
        public const string FIELDNAME_tbRegPatient__CreateDt = "TBREGPATIENT__CREATEDT";
        public const string FIELDNAME_tbRegPatient__Domain = "TBREGPATIENT__DOMAIN";
        public const string FIELDNAME_tbRegPatient__EnglishName = "TBREGPATIENT__ENGLISHNAME";
        public const string FIELDNAME_tbRegPatient__Gender = "TBREGPATIENT__GENDER";
        public const string FIELDNAME_tbRegPatient__GlobalID = "TBREGPATIENT__GLOBALID";
        public const string FIELDNAME_tbRegPatient__IsVIP = "TBREGPATIENT__ISVIP";
        public const string FIELDNAME_tbRegPatient__LocalName = "TBREGPATIENT__LOCALNAME";
        public const string FIELDNAME_tbRegPatient__Marriage = "TBREGPATIENT__MARRIAGE";
        public const string FIELDNAME_tbRegPatient__MedicareNo = "TBREGPATIENT__MEDICARENO";
        public const string FIELDNAME_tbRegPatient__Optional1 = "TBREGPATIENT__OPTIONAL1";
        public const string FIELDNAME_tbRegPatient__Optional2 = "TBREGPATIENT__OPTIONAL2";
        public const string FIELDNAME_tbRegPatient__Optional3 = "TBREGPATIENT__OPTIONAL3";
        public const string FIELDNAME_tbRegPatient__ParentName = "TBREGPATIENT__PARENTNAME";
        public const string FIELDNAME_tbRegPatient__PatientGuid = "TBREGPATIENT__PATIENTGUID";
        public const string FIELDNAME_tbRegPatient__PatientID = "TBREGPATIENT__PATIENTID";
        public const string FIELDNAME_tbRegPatient__ReferenceNo = "TBREGPATIENT__REFERENCENO";
        public const string FIELDNAME_tbRegPatient__RelatedID = "TBREGPATIENT__RELATEDID";
        public const string FIELDNAME_tbRegPatient__RemotePID = "TBREGPATIENT__REMOTEPID";
        public const string FIELDNAME_tbRegPatient__Site = "TBREGPATIENT__SITE";
        public const string FIELDNAME_tbRegPatient__SocialSecurityNo = "TBREGPATIENT__SOCIALSECURITYNO";
        public const string FIELDNAME_tbRegPatient__Telephone = "TBREGPATIENT__TELEPHONE";
        public const string FIELDNAME_tbRegPatient__UpdateTime = "TBREGPATIENT__UPDATETIME";
        public const string FIELDNAME_tbRegPatient__Uploaded = "TBREGPATIENT__UPLOADED";

        public const string FIELDNAME_tbRegOrder__AccNo = "TBREGORDER__ACCNO";
        public const string FIELDNAME_tbRegOrder__AgeInDays = "TBREGORDER__AGEINDAYS";
        public const string FIELDNAME_tbRegOrder__ApplyDept = "TBREGORDER__APPLYDEPT";
        public const string FIELDNAME_tbRegOrder__ApplyDoctor = "TBREGORDER__APPLYDOCTOR";
        public const string FIELDNAME_tbRegOrder__Assign2Site = "TBREGORDER__ASSIGN2SITE";
        public const string FIELDNAME_tbRegOrder__AssignDt = "TBREGORDER__ASSIGNDT";
        public const string FIELDNAME_tbRegOrder__BedNo = "TBREGORDER__BEDNO";
        public const string FIELDNAME_tbRegOrder__Bedside = "TBREGORDER__BEDSIDE";
        public const string FIELDNAME_tbRegOrder__BloodSugar = "TBREGORDER__BLOODSUGAR";
        public const string FIELDNAME_tbRegOrder__BodyHeight = "TBREGORDER__BODYHEIGHT";
        public const string FIELDNAME_tbRegOrder__BodyWeight = "TBREGORDER__BODYWEIGHT";
        public const string FIELDNAME_tbRegOrder__BookingSite = "TBREGORDER__BOOKINGSITE";
        public const string FIELDNAME_tbRegOrder__CardNo = "TBREGORDER__CARDNO";
        public const string FIELDNAME_tbRegOrder__ChargeType = "TBREGORDER__CHARGETYPE";
        public const string FIELDNAME_tbRegOrder__ClinicNo = "TBREGORDER__CLINICNO";
        public const string FIELDNAME_tbRegOrder__Comments = "TBREGORDER__COMMENTS";
        public const string FIELDNAME_tbRegOrder__CreateDt = "TBREGORDER__CREATEDT";
        public const string FIELDNAME_tbRegOrder__CurGender = "TBREGORDER__CURGENDER";
        public const string FIELDNAME_tbRegOrder__CurPatientName = "TBREGORDER__CURPATIENTNAME";
        public const string FIELDNAME_tbRegOrder__CurrentAge = "TBREGORDER__CURRENTAGE";
        public const string FIELDNAME_tbRegOrder__CurrentSite = "TBREGORDER__CURRENTSITE";
        public const string FIELDNAME_tbRegOrder__Domain = "TBREGORDER__DOMAIN";
        public const string FIELDNAME_tbRegOrder__ERequisition = "TBREGORDER__EREQUISITION";
        public const string FIELDNAME_tbRegOrder__ErethismCode = "TBREGORDER__ERETHISMCODE";
        public const string FIELDNAME_tbRegOrder__ErethismGrade = "TBREGORDER__ERETHISMGRADE";
        public const string FIELDNAME_tbRegOrder__ErethismType = "TBREGORDER__ERETHISMTYPE";
        public const string FIELDNAME_tbRegOrder__ExamAccNo = "TBREGORDER__EXAMACCNO";
        public const string FIELDNAME_tbRegOrder__EXAMALERT1 = "TBREGORDER__EXAMALERT1";
        public const string FIELDNAME_tbRegOrder__EXAMALERT2 = "TBREGORDER__EXAMALERT2";
        public const string FIELDNAME_tbRegOrder__ExamDomain = "TBREGORDER__EXAMDOMAIN";
        public const string FIELDNAME_tbRegOrder__ExamSite = "TBREGORDER__EXAMSITE";
        public const string FIELDNAME_tbRegOrder__ExternalOptional1 = "TBREGORDER__EXTERNALOPTIONAL1";
        public const string FIELDNAME_tbRegOrder__ExternalOptional2 = "TBREGORDER__EXTERNALOPTIONAL2";
        public const string FIELDNAME_tbRegOrder__ExternalOptional3 = "TBREGORDER__EXTERNALOPTIONAL3";
        public const string FIELDNAME_tbRegOrder__FilmFee = "TBREGORDER__FILMFEE";
        public const string FIELDNAME_tbRegOrder__FilmSentDt = "TBREGORDER__FILMSENTDT";
        public const string FIELDNAME_tbRegOrder__FilmSentOperator = "TBREGORDER__FILMSENTOPERATOR";
        public const string FIELDNAME_tbRegOrder__GoOnGoTime = "TBREGORDER__GOONGOTIME";
        public const string FIELDNAME_tbRegOrder__HealthHistory = "TBREGORDER__HEALTHHISTORY";
        public const string FIELDNAME_tbRegOrder__HisID = "TBREGORDER__HISID";
        public const string FIELDNAME_tbRegOrder__InhospitalNo = "TBREGORDER__INHOSPITALNO";
        public const string FIELDNAME_tbRegOrder__InhospitalRegion = "TBREGORDER__INHOSPITALREGION";
        public const string FIELDNAME_tbRegOrder__InitialDomain = "TBREGORDER__INITIALDOMAIN";
        public const string FIELDNAME_tbRegOrder__InjectDose = "TBREGORDER__INJECTDOSE";
        public const string FIELDNAME_tbRegOrder__InjectorRemnant = "TBREGORDER__INJECTORREMNANT";
        public const string FIELDNAME_tbRegOrder__InjectTime = "TBREGORDER__INJECTTIME";
        public const string FIELDNAME_tbRegOrder__Insulin = "TBREGORDER__INSULIN";
        public const string FIELDNAME_tbRegOrder__InternalOptional1 = "TBREGORDER__INTERNALOPTIONAL1";
        public const string FIELDNAME_tbRegOrder__InternalOptional2 = "TBREGORDER__INTERNALOPTIONAL2";
        public const string FIELDNAME_tbRegOrder__IsCharge = "TBREGORDER__ISCHARGE";
        public const string FIELDNAME_tbRegOrder__IsEmergency = "TBREGORDER__ISEMERGENCY";
        public const string FIELDNAME_tbRegOrder__IsFilmSent = "TBREGORDER__ISFILMSENT";
        public const string FIELDNAME_tbRegOrder__IsReferral = "TBREGORDER__ISREFERRAL";
        public const string FIELDNAME_tbRegOrder__IsScan = "TBREGORDER__ISSCAN";
        public const string FIELDNAME_tbRegOrder__LMP = "TBREGORDER__LMP";
        public const string FIELDNAME_tbRegOrder__MedicalAlert = "TBREGORDER__MEDICALALERT";
        public const string FIELDNAME_tbRegOrder__Observation = "TBREGORDER__OBSERVATION";
        public const string FIELDNAME_tbRegOrder__Optional1 = "TBREGORDER__OPTIONAL1";
        public const string FIELDNAME_tbRegOrder__Optional2 = "TBREGORDER__OPTIONAL2";
        public const string FIELDNAME_tbRegOrder__Optional3 = "TBREGORDER__OPTIONAL3";
        public const string FIELDNAME_tbRegOrder__OrderGuid = "TBREGORDER__ORDERGUID";
        public const string FIELDNAME_tbRegOrder__OrderMessage = "TBREGORDER__ORDERMESSAGE";
        public const string FIELDNAME_tbRegOrder__PathologicalFindings = "TBREGORDER__PATHOLOGICALFINDINGS";
        public const string FIELDNAME_tbRegOrder__PatientGuid = "TBREGORDER__PATIENTGUID";
        public const string FIELDNAME_tbRegOrder__PatientType = "TBREGORDER__PATIENTTYPE";
        public const string FIELDNAME_tbRegOrder__Priority = "TBREGORDER__PRIORITY";
        public const string FIELDNAME_tbRegOrder__ReferralID = "TBREGORDER__REFERRALID";
        public const string FIELDNAME_tbRegOrder__RegSite = "TBREGORDER__REGSITE";
        public const string FIELDNAME_tbRegOrder__RemoteAccNo = "TBREGORDER__REMOTEACCNO";
        public const string FIELDNAME_tbRegOrder__StudyID = "TBREGORDER__STUDYID";
        public const string FIELDNAME_tbRegOrder__StudyInstanceUID = "TBREGORDER__STUDYINSTANCEUID";
        public const string FIELDNAME_tbRegOrder__SubmitDept = "TBREGORDER__SUBMITDEPT";
        public const string FIELDNAME_tbRegOrder__SubmitDoctor = "TBREGORDER__SUBMITDOCTOR";
        public const string FIELDNAME_tbRegOrder__SubmitHospital = "TBREGORDER__SUBMITHOSPITAL";
        public const string FIELDNAME_tbRegOrder__TakeReportDate = "TBREGORDER__TAKEREPORTDATE";
        public const string FIELDNAME_tbRegOrder__ThreeDRebuild = "TBREGORDER__THREEDREBUILD";
        public const string FIELDNAME_tbRegOrder__TotalFee = "TBREGORDER__TOTALFEE";
        public const string FIELDNAME_tbRegOrder__UpdateTime = "TBREGORDER__UPDATETIME";
        public const string FIELDNAME_tbRegOrder__Uploaded = "TBREGORDER__UPLOADED";
        public const string FIELDNAME_tbRegOrder__visitcomment = "TBREGORDER__VISITCOMMENT";
        public const string FIELDNAME_tbRegOrder__VisitGuid = "TBREGORDER__VISITGUID";

        public const string FIELDNAME_tbRegProcedure__BodyCategory = "TBREGPROCEDURE__BODYCATEGORY";
        public const string FIELDNAME_tbRegProcedure__Bodypart = "TBREGPROCEDURE__BODYPART";
        public const string FIELDNAME_tbRegProcedure__Booker = "TBREGPROCEDURE__BOOKER";
        public const string FIELDNAME_tbRegProcedure__BookerName = "TBREGPROCEDURE__BOOKERNAME";
        public const string FIELDNAME_tbRegProcedure__BookingBeginDt = "TBREGPROCEDURE__BOOKINGBEGINDT";
        public const string FIELDNAME_tbRegProcedure__BookingEndDt = "TBREGPROCEDURE__BOOKINGENDDT";
        public const string FIELDNAME_tbRegProcedure__BookingNotice = "TBREGPROCEDURE__BOOKINGNOTICE";
        public const string FIELDNAME_tbRegProcedure__BookingTimeAlias = "TBREGPROCEDURE__BOOKINGTIMEALIAS";
        public const string FIELDNAME_tbRegProcedure__Charge = "TBREGPROCEDURE__CHARGE";
        public const string FIELDNAME_tbRegProcedure__CheckingItem = "TBREGPROCEDURE__CHECKINGITEM";
        public const string FIELDNAME_tbRegProcedure__Comments = "TBREGPROCEDURE__COMMENTS";
        public const string FIELDNAME_tbRegProcedure__ContrastDose = "TBREGPROCEDURE__CONTRASTDOSE";
        public const string FIELDNAME_tbRegProcedure__ContrastName = "TBREGPROCEDURE__CONTRASTNAME";
        public const string FIELDNAME_tbRegProcedure__CreateDt = "TBREGPROCEDURE__CREATEDT";
        public const string FIELDNAME_tbRegProcedure__Deposit = "TBREGPROCEDURE__DEPOSIT";
        public const string FIELDNAME_tbRegProcedure__Domain = "TBREGPROCEDURE__DOMAIN";
        public const string FIELDNAME_tbRegProcedure__ExamineDt = "TBREGPROCEDURE__EXAMINEDT";
        public const string FIELDNAME_tbRegProcedure__ExamSystem = "TBREGPROCEDURE__EXAMSYSTEM";
        public const string FIELDNAME_tbRegProcedure__ExposalCount = "TBREGPROCEDURE__EXPOSALCOUNT";
        public const string FIELDNAME_tbRegProcedure__FilmCount = "TBREGPROCEDURE__FILMCOUNT";
        public const string FIELDNAME_tbRegProcedure__FilmSpec = "TBREGPROCEDURE__FILMSPEC";
        public const string FIELDNAME_tbRegProcedure__ImageCount = "TBREGPROCEDURE__IMAGECOUNT";
        public const string FIELDNAME_tbRegProcedure__IsCharge = "TBREGPROCEDURE__ISCHARGE";
        public const string FIELDNAME_tbRegProcedure__IsExistImage = "TBREGPROCEDURE__ISEXISTIMAGE";
        public const string FIELDNAME_tbRegProcedure__IsPost = "TBREGPROCEDURE__ISPOST";
        public const string FIELDNAME_tbRegProcedure__MedicineUsage = "TBREGPROCEDURE__MEDICINEUSAGE";
        public const string FIELDNAME_tbRegProcedure__Mender = "TBREGPROCEDURE__MENDER";
        public const string FIELDNAME_tbRegProcedure__Modality = "TBREGPROCEDURE__MODALITY";
        public const string FIELDNAME_tbRegProcedure__ModalityType = "TBREGPROCEDURE__MODALITYTYPE";
        public const string FIELDNAME_tbRegProcedure__ModifyDt = "TBREGPROCEDURE__MODIFYDT";
        public const string FIELDNAME_tbRegProcedure__OperationStep = "TBREGPROCEDURE__OPERATIONSTEP";
        public const string FIELDNAME_tbRegProcedure__Optional1 = "TBREGPROCEDURE__OPTIONAL1";
        public const string FIELDNAME_tbRegProcedure__Optional2 = "TBREGPROCEDURE__OPTIONAL2";
        public const string FIELDNAME_tbRegProcedure__Optional3 = "TBREGPROCEDURE__OPTIONAL3";
        public const string FIELDNAME_tbRegProcedure__OrderGuid = "TBREGPROCEDURE__ORDERGUID";
        public const string FIELDNAME_tbRegProcedure__Posture = "TBREGPROCEDURE__POSTURE";
        public const string FIELDNAME_tbRegProcedure__PreStatus = "TBREGPROCEDURE__PRESTATUS";
        public const string FIELDNAME_tbRegProcedure__Priority = "TBREGPROCEDURE__PRIORITY";
        public const string FIELDNAME_tbRegProcedure__ProcedureCode = "TBREGPROCEDURE__PROCEDURECODE";
        public const string FIELDNAME_tbRegProcedure__ProcedureGuid = "TBREGPROCEDURE__PROCEDUREGUID";
        public const string FIELDNAME_tbRegProcedure__QueueNo = "TBREGPROCEDURE__QUEUENO";
        public const string FIELDNAME_tbRegProcedure__RegisterDt = "TBREGPROCEDURE__REGISTERDT";
        public const string FIELDNAME_tbRegProcedure__Registrar = "TBREGPROCEDURE__REGISTRAR";
        public const string FIELDNAME_tbRegProcedure__RegistrarName = "TBREGPROCEDURE__REGISTRARNAME";
        public const string FIELDNAME_tbRegProcedure__RemoteRPID = "TBREGPROCEDURE__REMOTERPID";
        public const string FIELDNAME_tbRegProcedure__ReportGuid = "TBREGPROCEDURE__REPORTGUID";
        public const string FIELDNAME_tbRegProcedure__RPDesc = "TBREGPROCEDURE__RPDESC";
        public const string FIELDNAME_tbRegProcedure__Status = "TBREGPROCEDURE__STATUS";
        public const string FIELDNAME_tbRegProcedure__TechDoctor = "TBREGPROCEDURE__TECHDOCTOR";
        public const string FIELDNAME_tbRegProcedure__Technician = "TBREGPROCEDURE__TECHNICIAN";
        public const string FIELDNAME_tbRegProcedure__Technician1 = "TBREGPROCEDURE__TECHNICIAN1";
        public const string FIELDNAME_tbRegProcedure__Technician2 = "TBREGPROCEDURE__TECHNICIAN2";
        public const string FIELDNAME_tbRegProcedure__Technician3 = "TBREGPROCEDURE__TECHNICIAN3";
        public const string FIELDNAME_tbRegProcedure__Technician4 = "TBREGPROCEDURE__TECHNICIAN4";
        public const string FIELDNAME_tbRegProcedure__TechnicianName = "TBREGPROCEDURE__TECHNICIANNAME";
        public const string FIELDNAME_tbRegProcedure__TechNurse = "TBREGPROCEDURE__TECHNURSE";
        public const string FIELDNAME_tbRegProcedure__UnapprovedAssignDate = "TBREGPROCEDURE__UNAPPROVEDASSIGNDATE";
        public const string FIELDNAME_tbRegProcedure__UnapprovedCurrentOwner = "TBREGPROCEDURE__UNAPPROVEDCURRENTOWNER";
        public const string FIELDNAME_tbRegProcedure__UnapprovedPreviousOwner = "TBREGPROCEDURE__UNAPPROVEDPREVIOUSOWNER";
        public const string FIELDNAME_tbRegProcedure__UnwrittenAssignDate = "TBREGPROCEDURE__UNWRITTENASSIGNDATE";
        public const string FIELDNAME_tbRegProcedure__UnwrittenCurrentOwner = "TBREGPROCEDURE__UNWRITTENCURRENTOWNER";
        public const string FIELDNAME_tbRegProcedure__UnwrittenPreviousOwner = "TBREGPROCEDURE__UNWRITTENPREVIOUSOWNER";
        public const string FIELDNAME_tbRegProcedure__UpdateTime = "TBREGPROCEDURE__UPDATETIME";
        public const string FIELDNAME_tbRegProcedure__Uploaded = "TBREGPROCEDURE__UPLOADED";
        public const string FIELDNAME_tbRegProcedure__WarningTime = "TBREGPROCEDURE__WARNINGTIME";

        public const string FIELDNAME_tbReport__AcrAnatomic = "TBREPORT__ACRANATOMIC";
        public const string FIELDNAME_tbReport__AcrCode = "TBREPORT__ACRCODE";
        public const string FIELDNAME_tbReport__AcrPathologic = "TBREPORT__ACRPATHOLOGIC";
        public const string FIELDNAME_tbReport__AppendInfo = "TBREPORT__APPENDINFO";
        public const string FIELDNAME_tbReport__CheckItemName = "TBREPORT__CHECKITEMNAME";
        public const string FIELDNAME_tbReport__CombinedForCertification = "TBREPORT__COMBINEDFORCERTIFICATION";
        public const string FIELDNAME_tbReport__Comments = "TBREPORT__COMMENTS";
        public const string FIELDNAME_tbReport__CreateDt = "TBREPORT__CREATEDT";
        public const string FIELDNAME_tbReport__Creater = "TBREPORT__CREATER";
        public const string FIELDNAME_tbReport__CreaterName = "TBREPORT__CREATERNAME";
        public const string FIELDNAME_tbReport__DeleteDt = "TBREPORT__DELETEDT";
        public const string FIELDNAME_tbReport__DeleteMark = "TBREPORT__DELETEMARK";
        public const string FIELDNAME_tbReport__Deleter = "TBREPORT__DELETER";
        public const string FIELDNAME_tbReport__DoctorAdvice = "TBREPORT__DOCTORADVICE";
        public const string FIELDNAME_tbReport__Domain = "TBREPORT__DOMAIN";
        public const string FIELDNAME_tbReport__DrawerSign = "TBREPORT__DRAWERSIGN";
        public const string FIELDNAME_tbReport__DrawTime = "TBREPORT__DRAWTIME";
        public const string FIELDNAME_tbReport__FirstApproveDomain = "TBREPORT__FIRSTAPPROVEDOMAIN";
        public const string FIELDNAME_tbReport__FirstApproveDt = "TBREPORT__FIRSTAPPROVEDT";
        public const string FIELDNAME_tbReport__FirstApprover = "TBREPORT__FIRSTAPPROVER";
        public const string FIELDNAME_tbReport__FirstApproverName = "TBREPORT__FIRSTAPPROVERNAME";
        public const string FIELDNAME_tbReport__FirstApproveSite = "TBREPORT__FIRSTAPPROVESITE";
        public const string FIELDNAME_tbReport__IsDiagnosisRight = "TBREPORT__ISDIAGNOSISRIGHT";
        public const string FIELDNAME_tbReport__IsDraw = "TBREPORT__ISDRAW";
        public const string FIELDNAME_tbReport__IsLeaveSound = "TBREPORT__ISLEAVESOUND";
        public const string FIELDNAME_tbReport__IsLeaveWord = "TBREPORT__ISLEAVEWORD";
        public const string FIELDNAME_tbReport__IsPositive = "TBREPORT__ISPOSITIVE";
        public const string FIELDNAME_tbReport__IsPrint = "TBREPORT__ISPRINT";
        public const string FIELDNAME_tbReport__KeyWord = "TBREPORT__KEYWORD";
        public const string FIELDNAME_tbReport__Mender = "TBREPORT__MENDER";
        public const string FIELDNAME_tbReport__MenderName = "TBREPORT__MENDERNAME";
        public const string FIELDNAME_tbReport__ModifyDt = "TBREPORT__MODIFYDT";
        public const string FIELDNAME_tbReport__Optional1 = "TBREPORT__OPTIONAL1";
        public const string FIELDNAME_tbReport__Optional2 = "TBREPORT__OPTIONAL2";
        public const string FIELDNAME_tbReport__Optional3 = "TBREPORT__OPTIONAL3";
        public const string FIELDNAME_tbReport__PrintCopies = "TBREPORT__PRINTCOPIES";
        public const string FIELDNAME_tbReport__PrintTemplateGuid = "TBREPORT__PRINTTEMPLATEGUID";
        public const string FIELDNAME_tbReport__ReadOnly = "TBREPORT__READONLY";
        public const string FIELDNAME_tbReport__RebuildMark = "TBREPORT__REBUILDMARK";
        public const string FIELDNAME_tbReport__ReconvertDt = "TBREPORT__RECONVERTDT";
        public const string FIELDNAME_tbReport__Recuperator = "TBREPORT__RECUPERATOR";
        public const string FIELDNAME_tbReport__RejectDomain = "TBREPORT__REJECTDOMAIN";
        public const string FIELDNAME_tbReport__RejectDt = "TBREPORT__REJECTDT";
        public const string FIELDNAME_tbReport__Rejecter = "TBREPORT__REJECTER";
        public const string FIELDNAME_tbReport__RejectSite = "TBREPORT__REJECTSITE";
        public const string FIELDNAME_tbReport__RejectToObject = "TBREPORT__REJECTTOOBJECT";
        public const string FIELDNAME_tbReport__ReportGuid = "TBREPORT__REPORTGUID";
        public const string FIELDNAME_tbReport__ReportName = "TBREPORT__REPORTNAME";
        public const string FIELDNAME_tbReport__ReportQuality = "TBREPORT__REPORTQUALITY";
        public const string FIELDNAME_tbReport__ReportQuality2 = "TBREPORT__REPORTQUALITY2";
        public const string FIELDNAME_tbReport__ReportQualityComments = "TBREPORT__REPORTQUALITYCOMMENTS";
        public const string FIELDNAME_tbReport__ReportText = "TBREPORT__REPORTTEXT";
        public const string FIELDNAME_tbReport__ReportTextApprovedSign = "TBREPORT__REPORTTEXTAPPROVEDSIGN";
        public const string FIELDNAME_tbReport__ReportTextSubmittedSign = "TBREPORT__REPORTTEXTSUBMITTEDSIGN";
        public const string FIELDNAME_tbReport__SecondApproveDomain = "TBREPORT__SECONDAPPROVEDOMAIN";
        public const string FIELDNAME_tbReport__SecondApproveDt = "TBREPORT__SECONDAPPROVEDT";
        public const string FIELDNAME_tbReport__SecondApprover = "TBREPORT__SECONDAPPROVER";
        public const string FIELDNAME_tbReport__SecondApproverName = "TBREPORT__SECONDAPPROVERNAME";
        public const string FIELDNAME_tbReport__SecondApproveSite = "TBREPORT__SECONDAPPROVESITE";
        public const string FIELDNAME_tbReport__SignCombinedForCertification = "TBREPORT__SIGNCOMBINEDFORCERTIFICATION";
        public const string FIELDNAME_tbReport__Status = "TBREPORT__STATUS";
        public const string FIELDNAME_tbReport__SubmitDomain = "TBREPORT__SUBMITDOMAIN";
        public const string FIELDNAME_tbReport__SubmitDt = "TBREPORT__SUBMITDT";
        public const string FIELDNAME_tbReport__SubmitSite = "TBREPORT__SUBMITSITE";
        public const string FIELDNAME_tbReport__Submitter = "TBREPORT__SUBMITTER";
        public const string FIELDNAME_tbReport__SubmitterName = "TBREPORT__SUBMITTERNAME";
        public const string FIELDNAME_tbReport__TakeFilmComment = "TBREPORT__TAKEFILMCOMMENT";
        public const string FIELDNAME_tbReport__TakeFilmDept = "TBREPORT__TAKEFILMDEPT";
        public const string FIELDNAME_tbReport__TakeFilmRegion = "TBREPORT__TAKEFILMREGION";
        public const string FIELDNAME_tbReport__TechInfo = "TBREPORT__TECHINFO";
        public const string FIELDNAME_tbReport__TerminalReportPrintNumber = "TBREPORT__TERMINALREPORTPRINTNUMBER";
        public const string FIELDNAME_tbReport__UpdateTime = "TBREPORT__UPDATETIME";
        public const string FIELDNAME_tbReport__Uploaded = "TBREPORT__UPLOADED";
        public const string FIELDNAME_tbReport__WYG = "TBREPORT__WYG";
        public const string FIELDNAME_tbReport__WYGText = "TBREPORT__WYGTEXT";
        public const string FIELDNAME_tbReport__WYS = "TBREPORT__WYS";
        public const string FIELDNAME_tbReport__WYSText = "TBREPORT__WYSTEXT";

        public const string FIELDNAME_PROCEDUREGUID = "tbRegProcedure__ProcedureGuid";
        public const string FIELDNAME_MODALITYTYPE = "tbRegProcedure__ModalityType";
        public const string FIELDNAME_TREGPROCEDURE_STATUS_DESC = "tbRegProcedure__Status__DESC";
        public const string FIELDNAME_TREGPROCEDURE_MODALITY = "tbRegProcedure__Modality";
        public const string FIELDNAME_TREGPROCEDURE_RPDESC = "tbRegProcedure__RPDesc";
        public const string FIELDNAME_TREGPROCEDURE_EXAMINEDT = "tbRegProcedure__ExamineDt";
        public const string FIELDNAME_VCONSULTATIONLIST_CSTAPPLYTIME = "vConsultationList__cstApplyTime";
        public const string FIELDNAME_VCONSULTATIONLIST_CSTGUID = "vConsultationList__cstGuid";
        public const string FIELDNAME_VCONSULTATIONLIST_CSTDIAGNOSISREQUESTID = "vConsultationList__cstDiagnosisRequestId";
        public const string FIELDNAME_VCONSULTATIONLIST_CSTSTATUS = "vConsultationList__cstStatus";
        public const string FIELDNAME_VCONSULTATIONLIST_CSTSTATUS__DESC = "vConsultationList__cstStatus__DESC";

        public const string FIELDNAME_EXAMNUMBER = "PATIENTEXAMNO";
        public const string FIELDNAME_CREATORSIGNIMAGE = "CREATORSIGN";
        public const string FIELDNAME_FIRSTAPPROVERSIGNIMAGE = "FIRSTAPPROVERSIGN";
        public const string FIELDNAME_SECONDAPPROVERSIGNIMAGE = "SECONDAPPROVERSIGN";
        public const string FIELDNAME_SUBMITTERSIGNIMAGE = "SUBMITTERSIGN";
    }
}
