//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18408.
// 
#pragma warning disable 1591

namespace Hys.Platform.Domain.Integration
{
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "HISConServiceSoap", Namespace = "http://HISConService")]
    public partial class HISConService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;

        private System.Threading.SendOrPostCallback getModelsInfoOperationCompleted;

        private System.Threading.SendOrPostCallback DoCommandOperationCompleted;

        private bool useDefaultCredentialsSetExplicitly;

        /// <remarks/>
        public HISConService(string url)
        {
            this.Url = url;
            if ((this.IsLocalFileSystemWebService(this.Url) == true))
            {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else
            {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }

        public new string Url
        {
            get
            {
                return base.Url;
            }
            set
            {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true)
                            && (this.useDefaultCredentialsSetExplicitly == false))
                            && (this.IsLocalFileSystemWebService(value) == false)))
                {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }

        public new bool UseDefaultCredentials
        {
            get
            {
                return base.UseDefaultCredentials;
            }
            set
            {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }

        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;

        /// <remarks/>
        public event getModelsInfoCompletedEventHandler getModelsInfoCompleted;

        /// <remarks/>
        public event DoCommandCompletedEventHandler DoCommandCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://HISConService/HelloWorld", RequestNamespace = "http://HISConService", ResponseNamespace = "http://HISConService", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld()
        {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void HelloWorldAsync()
        {
            this.HelloWorldAsync(null);
        }

        /// <remarks/>
        public void HelloWorldAsync(object userState)
        {
            if ((this.HelloWorldOperationCompleted == null))
            {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }

        private void OnHelloWorldOperationCompleted(object arg)
        {
            if ((this.HelloWorldCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://HISConService/getModelsInfo", RequestNamespace = "http://HISConService", ResponseNamespace = "http://HISConService", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ModelsInfo getModelsInfo()
        {
            object[] results = this.Invoke("getModelsInfo", new object[0]);
            return ((ModelsInfo)(results[0]));
        }

        /// <remarks/>
        public void getModelsInfoAsync()
        {
            this.getModelsInfoAsync(null);
        }

        /// <remarks/>
        public void getModelsInfoAsync(object userState)
        {
            if ((this.getModelsInfoOperationCompleted == null))
            {
                this.getModelsInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetModelsInfoOperationCompleted);
            }
            this.InvokeAsync("getModelsInfo", new object[0], this.getModelsInfoOperationCompleted, userState);
        }

        private void OngetModelsInfoOperationCompleted(object arg)
        {
            if ((this.getModelsInfoCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getModelsInfoCompleted(this, new getModelsInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://HISConService/DoCommand", RequestNamespace = "http://HISConService", ResponseNamespace = "http://HISConService", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DoCommand(string sToken, InputModel sCallingParamsInfo, ref ReturnModel sReturnInfo)
        {
            object[] results = this.Invoke("DoCommand", new object[] {
                        sToken,
                        sCallingParamsInfo,
                        sReturnInfo});
            sReturnInfo = ((ReturnModel)(results[0]));
        }

        /// <remarks/>
        public void DoCommandAsync(string sToken, InputModel sCallingParamsInfo, ReturnModel sReturnInfo)
        {
            this.DoCommandAsync(sToken, sCallingParamsInfo, sReturnInfo, null);
        }

        /// <remarks/>
        public void DoCommandAsync(string sToken, InputModel sCallingParamsInfo, ReturnModel sReturnInfo, object userState)
        {
            if ((this.DoCommandOperationCompleted == null))
            {
                this.DoCommandOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDoCommandOperationCompleted);
            }
            this.InvokeAsync("DoCommand", new object[] {
                        sToken,
                        sCallingParamsInfo,
                        sReturnInfo}, this.DoCommandOperationCompleted, userState);
        }

        private void OnDoCommandOperationCompleted(object arg)
        {
            if ((this.DoCommandCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DoCommandCompleted(this, new DoCommandCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }

        private bool IsLocalFileSystemWebService(string url)
        {
            if (((url == null)
                        || (url == string.Empty)))
            {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024)
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0)))
            {
                return true;
            }
            return false;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://HISConService")]
    public partial class ModelsInfo
    {

        private SharedInfo sharedinfoField;

        private ReturnModel returnModelField;

        private GetQueueInfoBodyReturnModel queuebodyField;

        private GetRequestInfoBodyReturnModel requestbodyField;

        private InputModel inputModelField;

        private GetQueueInfoBodyInputModel queueBodyField;

        private GetRequestInfoBodyInputModel requestBodyField;

        private UpdateBookInfoBodyInputModel bookingBodyField;

        /// <remarks/>
        public SharedInfo sharedinfo
        {
            get
            {
                return this.sharedinfoField;
            }
            set
            {
                this.sharedinfoField = value;
            }
        }

        /// <remarks/>
        public ReturnModel returnModel
        {
            get
            {
                return this.returnModelField;
            }
            set
            {
                this.returnModelField = value;
            }
        }

        /// <remarks/>
        public GetQueueInfoBodyReturnModel queuebody
        {
            get
            {
                return this.queuebodyField;
            }
            set
            {
                this.queuebodyField = value;
            }
        }

        /// <remarks/>
        public GetRequestInfoBodyReturnModel requestbody
        {
            get
            {
                return this.requestbodyField;
            }
            set
            {
                this.requestbodyField = value;
            }
        }

        /// <remarks/>
        public InputModel inputModel
        {
            get
            {
                return this.inputModelField;
            }
            set
            {
                this.inputModelField = value;
            }
        }

        /// <remarks/>
        public GetQueueInfoBodyInputModel queueBody
        {
            get
            {
                return this.queueBodyField;
            }
            set
            {
                this.queueBodyField = value;
            }
        }

        /// <remarks/>
        public GetRequestInfoBodyInputModel requestBody
        {
            get
            {
                return this.requestBodyField;
            }
            set
            {
                this.requestBodyField = value;
            }
        }

        /// <remarks/>
        public UpdateBookInfoBodyInputModel bookingBody
        {
            get
            {
                return this.bookingBodyField;
            }
            set
            {
                this.bookingBodyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://HISConService")]
    public partial class SharedInfo
    {
        public const string BodyVersion1 = "1.0.1.0";

        public const string MessageID_GetRequestInfo = "GetRequestInfo";// 获取检查申请信息
        public const string MessageID_GetQueueInfo = "GetQueueInfo"; //获取检查排队信息
        public const string MessageID_BroadcastQueueInfo = "BroadcastQueueInfo"; //叫号
        public const string MessageID_UpdateChargeInfo = "UpdateChargeInfo"; // 费用信息更新
        public const string MessageID_ConvertURLInfo = "ConvertURLInfo"; // 转换URL对应的内容
        public const string MessageID_UpdateBookInfo = "UpdateBookInfo"; // 转换URL对应的内容

        public const string BodyFormat_STRING = "STRING";
        public const string BodyFormat_XML = "XML";
        public const string BodyFormat_JSON = "JSON";

        public const string SystemID_HISCON = "HISCON";
        public const string SystemID_RISGC = "RISGC";

        public const string ChargeItemSource_OP = "OP";
        public const string ChargeItemSource_RISGC = "RISGC";

        public enum CalledResult
        {
            Q_SUCCESS = 0,
            Q_DBEXCEPTION = 1001,
            Q_OPENDBFAIL = 1002,
            Q_QUESYSFAIL = 1003,
            Q_QUESYSDOWN = 1004
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2001/XMLSchema")]
    public partial class RequestItem2
    {

        private string requestItemUIDField;

        private string requestItemNameField;

        private string requestItemCodeField;

        private string requestTeethNameField;

        private string requestTeethCodeField;

        private string requestTeethCountField;

        private string modalityTypeField;

        private string modalityField;

        private string scheduledDateTimeField;

        /// <remarks/>
        public string RequestItemUID
        {
            get
            {
                return this.requestItemUIDField;
            }
            set
            {
                this.requestItemUIDField = value;
            }
        }

        /// <remarks/>
        public string RequestItemName
        {
            get
            {
                return this.requestItemNameField;
            }
            set
            {
                this.requestItemNameField = value;
            }
        }

        /// <remarks/>
        public string RequestItemCode
        {
            get
            {
                return this.requestItemCodeField;
            }
            set
            {
                this.requestItemCodeField = value;
            }
        }

        /// <remarks/>
        public string RequestTeethName
        {
            get
            {
                return this.requestTeethNameField;
            }
            set
            {
                this.requestTeethNameField = value;
            }
        }

        /// <remarks/>
        public string RequestTeethCode
        {
            get
            {
                return this.requestTeethCodeField;
            }
            set
            {
                this.requestTeethCodeField = value;
            }
        }

        /// <remarks/>
        public string RequestTeethCount
        {
            get
            {
                return this.requestTeethCountField;
            }
            set
            {
                this.requestTeethCountField = value;
            }
        }

        /// <remarks/>
        public string ModalityType
        {
            get
            {
                return this.modalityTypeField;
            }
            set
            {
                this.modalityTypeField = value;
            }
        }

        /// <remarks/>
        public string Modality
        {
            get
            {
                return this.modalityField;
            }
            set
            {
                this.modalityField = value;
            }
        }

        /// <remarks/>
        public string ScheduledDateTime
        {
            get
            {
                return this.scheduledDateTimeField;
            }
            set
            {
                this.scheduledDateTimeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2001/XMLSchema")]
    public partial class Patient2
    {

        private string marriageField;

        /// <remarks/>
        public string Marriage
        {
            get
            {
                return this.marriageField;
            }
            set
            {
                this.marriageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2001/XMLSchema")]
    public partial class PatientInfo2
    {

        private string localNameField;

        private string patientIDField;

        private System.DateTime birthDateField;

        private string genderField;

        private string addressField;

        private string hISIDField;

        private string referenceNoField;

        private string socailSecurityNoField;

        private string medicareNoField;

        private string telephoneField;

        private string globalIDField;

        private string isVIPField;

        private string matchKeyField;

        private Patient2 patientField;

        /// <remarks/>
        public string LocalName
        {
            get
            {
                return this.localNameField;
            }
            set
            {
                this.localNameField = value;
            }
        }

        /// <remarks/>
        public string PatientID
        {
            get
            {
                return this.patientIDField;
            }
            set
            {
                this.patientIDField = value;
            }
        }

        /// <remarks/>
        public System.DateTime BirthDate
        {
            get
            {
                return this.birthDateField;
            }
            set
            {
                this.birthDateField = value;
            }
        }

        /// <remarks/>
        public string Gender
        {
            get
            {
                return this.genderField;
            }
            set
            {
                this.genderField = value;
            }
        }

        /// <remarks/>
        public string Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }

        /// <remarks/>
        public string HISID
        {
            get
            {
                return this.hISIDField;
            }
            set
            {
                this.hISIDField = value;
            }
        }

        /// <remarks/>
        public string ReferenceNo
        {
            get
            {
                return this.referenceNoField;
            }
            set
            {
                this.referenceNoField = value;
            }
        }

        /// <remarks/>
        public string SocailSecurityNo
        {
            get
            {
                return this.socailSecurityNoField;
            }
            set
            {
                this.socailSecurityNoField = value;
            }
        }

        /// <remarks/>
        public string MedicareNo
        {
            get
            {
                return this.medicareNoField;
            }
            set
            {
                this.medicareNoField = value;
            }
        }

        /// <remarks/>
        public string Telephone
        {
            get
            {
                return this.telephoneField;
            }
            set
            {
                this.telephoneField = value;
            }
        }

        /// <remarks/>
        public string GlobalID
        {
            get
            {
                return this.globalIDField;
            }
            set
            {
                this.globalIDField = value;
            }
        }

        /// <remarks/>
        public string IsVIP
        {
            get
            {
                return this.isVIPField;
            }
            set
            {
                this.isVIPField = value;
            }
        }

        /// <remarks/>
        public string MatchKey
        {
            get
            {
                return this.matchKeyField;
            }
            set
            {
                this.matchKeyField = value;
            }
        }

        /// <remarks/>
        public Patient2 Patient
        {
            get
            {
                return this.patientField;
            }
            set
            {
                this.patientField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2001/XMLSchema")]
    public partial class UpdateBookInfoBodyInputModel
    {

        private string requestFormNameField;

        private string eRNoField;

        private PatientInfo2 patientInfoField;

        private RequestItem2[] requestItemsField;

        /// <remarks/>
        public string RequestFormName
        {
            get
            {
                return this.requestFormNameField;
            }
            set
            {
                this.requestFormNameField = value;
            }
        }

        /// <remarks/>
        public string ERNo
        {
            get
            {
                return this.eRNoField;
            }
            set
            {
                this.eRNoField = value;
            }
        }

        /// <remarks/>
        public PatientInfo2 PatientInfo
        {
            get
            {
                return this.patientInfoField;
            }
            set
            {
                this.patientInfoField = value;
            }
        }

        /// <remarks/>
        public RequestItem2[] RequestItems
        {
            get
            {
                return this.requestItemsField;
            }
            set
            {
                this.requestItemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2001/XMLSchema")]
    public partial class GetRequestInfoBodyInputModel
    {

        private string cardTypeField;

        private string cardNumberField;

        private string operatorLocalNameField;

        private string operatorLoginNameField;

        private string terminalNameField;

        /// <remarks/>
        public string CardType
        {
            get
            {
                return this.cardTypeField;
            }
            set
            {
                this.cardTypeField = value;
            }
        }

        /// <remarks/>
        public string CardNumber
        {
            get
            {
                return this.cardNumberField;
            }
            set
            {
                this.cardNumberField = value;
            }
        }

        /// <remarks/>
        public string OperatorLocalName
        {
            get
            {
                return this.operatorLocalNameField;
            }
            set
            {
                this.operatorLocalNameField = value;
            }
        }

        /// <remarks/>
        public string OperatorLoginName
        {
            get
            {
                return this.operatorLoginNameField;
            }
            set
            {
                this.operatorLoginNameField = value;
            }
        }

        /// <remarks/>
        public string TerminalName
        {
            get
            {
                return this.terminalNameField;
            }
            set
            {
                this.terminalNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2001/XMLSchema")]
    public partial class GetQueueInfoBodyInputModel
    {

        private string patientIDField;

        private string patientTypeField;

        private string patientNameField;

        private decimal operationTypeField;

        private string dwFlagsField;

        private string globalQueueNumberField;

        private string accNumberField;

        private string examTypeField;

        private string examModalityField;

        private string examRoomIDField;

        private string examRoomField;

        private string bookedExamTimePartField;

        private string noteField;

        private string operatorLocalNameField;

        private string operatorLoginNameField;

        private string terminalNameField;

        /// <remarks/>
        public string PatientID
        {
            get
            {
                return this.patientIDField;
            }
            set
            {
                this.patientIDField = value;
            }
        }

        /// <remarks/>
        public string PatientType
        {
            get
            {
                return this.patientTypeField;
            }
            set
            {
                this.patientTypeField = value;
            }
        }

        /// <remarks/>
        public string PatientName
        {
            get
            {
                return this.patientNameField;
            }
            set
            {
                this.patientNameField = value;
            }
        }

        /// <remarks/>
        public decimal OperationType
        {
            get
            {
                return this.operationTypeField;
            }
            set
            {
                this.operationTypeField = value;
            }
        }

        /// <remarks/>
        public string dwFlags
        {
            get
            {
                return this.dwFlagsField;
            }
            set
            {
                this.dwFlagsField = value;
            }
        }

        /// <remarks/>
        public string GlobalQueueNumber
        {
            get
            {
                return this.globalQueueNumberField;
            }
            set
            {
                this.globalQueueNumberField = value;
            }
        }

        /// <remarks/>
        public string AccNumber
        {
            get
            {
                return this.accNumberField;
            }
            set
            {
                this.accNumberField = value;
            }
        }

        /// <remarks/>
        public string ExamType
        {
            get
            {
                return this.examTypeField;
            }
            set
            {
                this.examTypeField = value;
            }
        }

        /// <remarks/>
        public string ExamModality
        {
            get
            {
                return this.examModalityField;
            }
            set
            {
                this.examModalityField = value;
            }
        }

        /// <remarks/>
        public string ExamRoomID
        {
            get
            {
                return this.examRoomIDField;
            }
            set
            {
                this.examRoomIDField = value;
            }
        }

        /// <remarks/>
        public string ExamRoom
        {
            get
            {
                return this.examRoomField;
            }
            set
            {
                this.examRoomField = value;
            }
        }

        /// <remarks/>
        public string BookedExamTimePart
        {
            get
            {
                return this.bookedExamTimePartField;
            }
            set
            {
                this.bookedExamTimePartField = value;
            }
        }

        /// <remarks/>
        public string Note
        {
            get
            {
                return this.noteField;
            }
            set
            {
                this.noteField = value;
            }
        }

        /// <remarks/>
        public string OperatorLocalName
        {
            get
            {
                return this.operatorLocalNameField;
            }
            set
            {
                this.operatorLocalNameField = value;
            }
        }

        /// <remarks/>
        public string OperatorLoginName
        {
            get
            {
                return this.operatorLoginNameField;
            }
            set
            {
                this.operatorLoginNameField = value;
            }
        }

        /// <remarks/>
        public string TerminalName
        {
            get
            {
                return this.terminalNameField;
            }
            set
            {
                this.terminalNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://HISConService")]
    public partial class InputModel
    {

        private string messageIDField;

        private string messageBodyFormatField;

        private string messageBodyVersionField;

        private string messageBodyField;

        /// <remarks/>
        public string MessageID
        {
            get
            {
                return this.messageIDField;
            }
            set
            {
                this.messageIDField = value;
            }
        }

        /// <remarks/>
        public string MessageBodyFormat
        {
            get
            {
                return this.messageBodyFormatField;
            }
            set
            {
                this.messageBodyFormatField = value;
            }
        }

        /// <remarks/>
        public string MessageBodyVersion
        {
            get
            {
                return this.messageBodyVersionField;
            }
            set
            {
                this.messageBodyVersionField = value;
            }
        }

        /// <remarks/>
        public string MessageBody
        {
            get
            {
                return this.messageBodyField;
            }
            set
            {
                this.messageBodyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "CaretreamHealth.GCRIS.HISCon.ReturnModels")]
    public partial class Extension1
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "CaretreamHealth.GCRIS.HISCon.ReturnModels")]
    public partial class Extension2
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "CaretreamHealth.GCRIS.HISCon.ReturnModels")]
    public partial class Extension3
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "CaretreamHealth.GCRIS.HISCon.ReturnModels")]
    public partial class Procedure
    {

        private string contrastNameField;

        private string contrastDoseField;

        /// <remarks/>
        public string ContrastName
        {
            get
            {
                return this.contrastNameField;
            }
            set
            {
                this.contrastNameField = value;
            }
        }

        /// <remarks/>
        public string ContrastDose
        {
            get
            {
                return this.contrastDoseField;
            }
            set
            {
                this.contrastDoseField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "CaretreamHealth.GCRIS.HISCon.ReturnModels")]
    public partial class ChargeItem
    {

        private string chargeItemCodeField;

        private string chargeItemSumField;

        private string chargeItemAmountField;

        private string chargeItemUnitPriceField;

        private string chargeItemUnitField;

        private string chargeItemSourceField;

        private string isItemChargedField;

        /// <remarks/>
        public string ChargeItemCode
        {
            get
            {
                return this.chargeItemCodeField;
            }
            set
            {
                this.chargeItemCodeField = value;
            }
        }

        /// <remarks/>
        public string ChargeItemSum
        {
            get
            {
                return this.chargeItemSumField;
            }
            set
            {
                this.chargeItemSumField = value;
            }
        }

        /// <remarks/>
        public string ChargeItemAmount
        {
            get
            {
                return this.chargeItemAmountField;
            }
            set
            {
                this.chargeItemAmountField = value;
            }
        }

        /// <remarks/>
        public string ChargeItemUnitPrice
        {
            get
            {
                return this.chargeItemUnitPriceField;
            }
            set
            {
                this.chargeItemUnitPriceField = value;
            }
        }

        /// <remarks/>
        public string ChargeItemUnit
        {
            get
            {
                return this.chargeItemUnitField;
            }
            set
            {
                this.chargeItemUnitField = value;
            }
        }

        /// <remarks/>
        public string ChargeItemSource
        {
            get
            {
                return this.chargeItemSourceField;
            }
            set
            {
                this.chargeItemSourceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IsItemCharged
        {
            get
            {
                return this.isItemChargedField;
            }
            set
            {
                this.isItemChargedField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "CaretreamHealth.GCRIS.HISCon.ReturnModels")]
    public partial class ChargeInfo
    {

        private ChargeItem[] chargeItemsField;

        private string totalChargeField;

        private string isChargedField;

        /// <remarks/>
        public ChargeItem[] ChargeItems
        {
            get
            {
                return this.chargeItemsField;
            }
            set
            {
                this.chargeItemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TotalCharge
        {
            get
            {
                return this.totalChargeField;
            }
            set
            {
                this.totalChargeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IsCharged
        {
            get
            {
                return this.isChargedField;
            }
            set
            {
                this.isChargedField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "CaretreamHealth.GCRIS.HISCon.ReturnModels")]
    public partial class ScheduleInfo
    {

        private string scheduleUIDField;

        private string scheduleTypeField;

        private string scheduleStatusField;

        private System.DateTime scheduledDateTimeField;

        private string scheduledModalityField;

        /// <remarks/>
        public string ScheduleUID
        {
            get
            {
                return this.scheduleUIDField;
            }
            set
            {
                this.scheduleUIDField = value;
            }
        }

        /// <remarks/>
        public string ScheduleType
        {
            get
            {
                return this.scheduleTypeField;
            }
            set
            {
                this.scheduleTypeField = value;
            }
        }

        /// <remarks/>
        public string ScheduleStatus
        {
            get
            {
                return this.scheduleStatusField;
            }
            set
            {
                this.scheduleStatusField = value;
            }
        }

        /// <remarks/>
        public System.DateTime ScheduledDateTime
        {
            get
            {
                return this.scheduledDateTimeField;
            }
            set
            {
                this.scheduledDateTimeField = value;
            }
        }

        /// <remarks/>
        public string ScheduledModality
        {
            get
            {
                return this.scheduledModalityField;
            }
            set
            {
                this.scheduledModalityField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "CaretreamHealth.GCRIS.HISCon.ReturnModels")]
    public partial class RequestItem
    {

        private string requestItemUIDField;

        private string requestItemNameField;

        private string requestItemCodeField;

        private string requestTeethNameField;

        private string requestTeethCodeField;

        private string requestTeethCountField;

        private string modalityTypeField;

        private string modalityField;

        private string requestItemCommentsField;

        private ScheduleInfo scheduleInfoField;

        private ChargeInfo chargeInfoField;

        private Procedure procedureField;

        private Extension3 extension3Field;

        /// <remarks/>
        public string RequestItemUID
        {
            get
            {
                return this.requestItemUIDField;
            }
            set
            {
                this.requestItemUIDField = value;
            }
        }

        /// <remarks/>
        public string RequestItemName
        {
            get
            {
                return this.requestItemNameField;
            }
            set
            {
                this.requestItemNameField = value;
            }
        }

        /// <remarks/>
        public string RequestItemCode
        {
            get
            {
                return this.requestItemCodeField;
            }
            set
            {
                this.requestItemCodeField = value;
            }
        }

        /// <remarks/>
        public string RequestTeethName
        {
            get
            {
                return this.requestTeethNameField;
            }
            set
            {
                this.requestTeethNameField = value;
            }
        }

        /// <remarks/>
        public string RequestTeethCode
        {
            get
            {
                return this.requestTeethCodeField;
            }
            set
            {
                this.requestTeethCodeField = value;
            }
        }

        /// <remarks/>
        public string RequestTeethCount
        {
            get
            {
                return this.requestTeethCountField;
            }
            set
            {
                this.requestTeethCountField = value;
            }
        }

        /// <remarks/>
        public string ModalityType
        {
            get
            {
                return this.modalityTypeField;
            }
            set
            {
                this.modalityTypeField = value;
            }
        }

        /// <remarks/>
        public string Modality
        {
            get
            {
                return this.modalityField;
            }
            set
            {
                this.modalityField = value;
            }
        }

        /// <remarks/>
        public string RequestItemComments
        {
            get
            {
                return this.requestItemCommentsField;
            }
            set
            {
                this.requestItemCommentsField = value;
            }
        }

        /// <remarks/>
        public ScheduleInfo ScheduleInfo
        {
            get
            {
                return this.scheduleInfoField;
            }
            set
            {
                this.scheduleInfoField = value;
            }
        }

        /// <remarks/>
        public ChargeInfo ChargeInfo
        {
            get
            {
                return this.chargeInfoField;
            }
            set
            {
                this.chargeInfoField = value;
            }
        }

        /// <remarks/>
        public Procedure Procedure
        {
            get
            {
                return this.procedureField;
            }
            set
            {
                this.procedureField = value;
            }
        }

        /// <remarks/>
        public Extension3 Extension3
        {
            get
            {
                return this.extension3Field;
            }
            set
            {
                this.extension3Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "CaretreamHealth.GCRIS.HISCon.ReturnModels")]
    public partial class RequestDetailsInfo
    {

        private RequestItem[] requestItemsField;

        private ChargeInfo chargeInfoField;

        /// <remarks/>
        public RequestItem[] RequestItems
        {
            get
            {
                return this.requestItemsField;
            }
            set
            {
                this.requestItemsField = value;
            }
        }

        /// <remarks/>
        public ChargeInfo ChargeInfo
        {
            get
            {
                return this.chargeInfoField;
            }
            set
            {
                this.chargeInfoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "CaretreamHealth.GCRIS.HISCon.ReturnModels")]
    public partial class Order
    {

        private string bedNoField;

        private string inHospitalRegionField;

        private string currentAgeField;

        private string bedSideField;

        private string threedRebuildField;

        private string requestTypeField;

        /// <remarks/>
        public string BedNo
        {
            get
            {
                return this.bedNoField;
            }
            set
            {
                this.bedNoField = value;
            }
        }

        /// <remarks/>
        public string InHospitalRegion
        {
            get
            {
                return this.inHospitalRegionField;
            }
            set
            {
                this.inHospitalRegionField = value;
            }
        }

        /// <remarks/>
        public string CurrentAge
        {
            get
            {
                return this.currentAgeField;
            }
            set
            {
                this.currentAgeField = value;
            }
        }

        /// <remarks/>
        public string BedSide
        {
            get
            {
                return this.bedSideField;
            }
            set
            {
                this.bedSideField = value;
            }
        }

        /// <remarks/>
        public string ThreedRebuild
        {
            get
            {
                return this.threedRebuildField;
            }
            set
            {
                this.threedRebuildField = value;
            }
        }

        /// <remarks/>
        public string RequestType
        {
            get
            {
                return this.requestTypeField;
            }
            set
            {
                this.requestTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "CaretreamHealth.GCRIS.HISCon.ReturnModels")]
    public partial class RequestInfo
    {

        private string requestFormNameField;

        private string eRNoField;

        private string patientTypeField;

        private string inhospitalNoField;

        private string clinicNoField;

        private string applyDeptField;

        private string applyDeptNoField;

        private string applyDoctorField;

        private string applyDoctorIDField;

        private System.DateTime applyDateTimeField;

        private string observationField;

        private string healthHistoryField;

        private string commentsField;

        private string chargeTypeField;

        private string teethPositionField;

        private string eAcquisitionURLField;

        private Order orderField;

        /// <remarks/>
        public string RequestFormName
        {
            get
            {
                return this.requestFormNameField;
            }
            set
            {
                this.requestFormNameField = value;
            }
        }

        /// <remarks/>
        public string ERNo
        {
            get
            {
                return this.eRNoField;
            }
            set
            {
                this.eRNoField = value;
            }
        }

        /// <remarks/>
        public string PatientType
        {
            get
            {
                return this.patientTypeField;
            }
            set
            {
                this.patientTypeField = value;
            }
        }

        /// <remarks/>
        public string InhospitalNo
        {
            get
            {
                return this.inhospitalNoField;
            }
            set
            {
                this.inhospitalNoField = value;
            }
        }

        /// <remarks/>
        public string ClinicNo
        {
            get
            {
                return this.clinicNoField;
            }
            set
            {
                this.clinicNoField = value;
            }
        }

        /// <remarks/>
        public string ApplyDept
        {
            get
            {
                return this.applyDeptField;
            }
            set
            {
                this.applyDeptField = value;
            }
        }

        /// <remarks/>
        public string ApplyDeptNo
        {
            get
            {
                return this.applyDeptNoField;
            }
            set
            {
                this.applyDeptNoField = value;
            }
        }

        /// <remarks/>
        public string ApplyDoctor
        {
            get
            {
                return this.applyDoctorField;
            }
            set
            {
                this.applyDoctorField = value;
            }
        }

        /// <remarks/>
        public string ApplyDoctorID
        {
            get
            {
                return this.applyDoctorIDField;
            }
            set
            {
                this.applyDoctorIDField = value;
            }
        }

        /// <remarks/>
        public System.DateTime ApplyDateTime
        {
            get
            {
                return this.applyDateTimeField;
            }
            set
            {
                this.applyDateTimeField = value;
            }
        }

        /// <remarks/>
        public string Observation
        {
            get
            {
                return this.observationField;
            }
            set
            {
                this.observationField = value;
            }
        }

        /// <remarks/>
        public string HealthHistory
        {
            get
            {
                return this.healthHistoryField;
            }
            set
            {
                this.healthHistoryField = value;
            }
        }

        /// <remarks/>
        public string Comments
        {
            get
            {
                return this.commentsField;
            }
            set
            {
                this.commentsField = value;
            }
        }

        /// <remarks/>
        public string ChargeType
        {
            get
            {
                return this.chargeTypeField;
            }
            set
            {
                this.chargeTypeField = value;
            }
        }

        /// <remarks/>
        public string TeethPosition
        {
            get
            {
                return this.teethPositionField;
            }
            set
            {
                this.teethPositionField = value;
            }
        }

        /// <remarks/>
        public string EAcquisitionURL
        {
            get
            {
                return this.eAcquisitionURLField;
            }
            set
            {
                this.eAcquisitionURLField = value;
            }
        }

        /// <remarks/>
        public Order Order
        {
            get
            {
                return this.orderField;
            }
            set
            {
                this.orderField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "CaretreamHealth.GCRIS.HISCon.ReturnModels")]
    public partial class Request
    {

        private RequestInfo requestInfoField;

        private RequestDetailsInfo requestDetailInfoField;

        private Extension2 extension2Field;

        /// <remarks/>
        public RequestInfo RequestInfo
        {
            get
            {
                return this.requestInfoField;
            }
            set
            {
                this.requestInfoField = value;
            }
        }

        /// <remarks/>
        public RequestDetailsInfo RequestDetailInfo
        {
            get
            {
                return this.requestDetailInfoField;
            }
            set
            {
                this.requestDetailInfoField = value;
            }
        }

        /// <remarks/>
        public Extension2 Extension2
        {
            get
            {
                return this.extension2Field;
            }
            set
            {
                this.extension2Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "CaretreamHealth.GCRIS.HISCon.ReturnModels")]
    public partial class Patient
    {

        private string marriageField;

        /// <remarks/>
        public string Marriage
        {
            get
            {
                return this.marriageField;
            }
            set
            {
                this.marriageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "CaretreamHealth.GCRIS.HISCon.ReturnModels")]
    public partial class PatientInfo
    {

        private string localNameField;

        private string patientIDField;

        private System.DateTime birthDateField;

        private string genderField;

        private string addressField;

        private string hISIDField;

        private string referenceNoField;

        private string socailSecurityNoField;

        private string medicareNoField;

        private string telephoneField;

        private string globalIDField;

        private string isVIPField;

        private string matchKeyField;

        private Patient patientField;

        /// <remarks/>
        public string LocalName
        {
            get
            {
                return this.localNameField;
            }
            set
            {
                this.localNameField = value;
            }
        }

        /// <remarks/>
        public string PatientID
        {
            get
            {
                return this.patientIDField;
            }
            set
            {
                this.patientIDField = value;
            }
        }

        /// <remarks/>
        public System.DateTime BirthDate
        {
            get
            {
                return this.birthDateField;
            }
            set
            {
                this.birthDateField = value;
            }
        }

        /// <remarks/>
        public string Gender
        {
            get
            {
                return this.genderField;
            }
            set
            {
                this.genderField = value;
            }
        }

        /// <remarks/>
        public string Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }

        /// <remarks/>
        public string HISID
        {
            get
            {
                return this.hISIDField;
            }
            set
            {
                this.hISIDField = value;
            }
        }

        /// <remarks/>
        public string ReferenceNo
        {
            get
            {
                return this.referenceNoField;
            }
            set
            {
                this.referenceNoField = value;
            }
        }

        /// <remarks/>
        public string SocailSecurityNo
        {
            get
            {
                return this.socailSecurityNoField;
            }
            set
            {
                this.socailSecurityNoField = value;
            }
        }

        /// <remarks/>
        public string MedicareNo
        {
            get
            {
                return this.medicareNoField;
            }
            set
            {
                this.medicareNoField = value;
            }
        }

        /// <remarks/>
        public string Telephone
        {
            get
            {
                return this.telephoneField;
            }
            set
            {
                this.telephoneField = value;
            }
        }

        /// <remarks/>
        public string GlobalID
        {
            get
            {
                return this.globalIDField;
            }
            set
            {
                this.globalIDField = value;
            }
        }

        /// <remarks/>
        public string IsVIP
        {
            get
            {
                return this.isVIPField;
            }
            set
            {
                this.isVIPField = value;
            }
        }

        /// <remarks/>
        public string MatchKey
        {
            get
            {
                return this.matchKeyField;
            }
            set
            {
                this.matchKeyField = value;
            }
        }

        /// <remarks/>
        public Patient Patient
        {
            get
            {
                return this.patientField;
            }
            set
            {
                this.patientField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "CaretreamHealth.GCRIS.HISCon.ReturnModels")]
    public partial class GetRequestInfoBodyReturnModel
    {

        private PatientInfo patientInfoField;

        private Request[] requestsField;

        private Extension1 extension1Field;

        /// <remarks/>
        public PatientInfo PatientInfo
        {
            get
            {
                return this.patientInfoField;
            }
            set
            {
                this.patientInfoField = value;
            }
        }

        /// <remarks/>
        public Request[] Requests
        {
            get
            {
                return this.requestsField;
            }
            set
            {
                this.requestsField = value;
            }
        }

        /// <remarks/>
        public Extension1 Extension1
        {
            get
            {
                return this.extension1Field;
            }
            set
            {
                this.extension1Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "CaretreamHealth.GCRIS.HISCon.ReturnModels")]
    public partial class GetQueueInfoBodyReturnModel
    {

        private string accNumberField;

        private string globalQueueNumberField;

        private string roomQueueNumberField;

        private string examRoomIDField;

        private string examRoomField;

        private string globalAmountOfUnfinishedField;

        private string roomAmountOfUnfinishedField;

        private System.DateTime plannedExamDateTimeInQueueField;

        private string noteField;

        /// <remarks/>
        public string AccNumber
        {
            get
            {
                return this.accNumberField;
            }
            set
            {
                this.accNumberField = value;
            }
        }

        /// <remarks/>
        public string GlobalQueueNumber
        {
            get
            {
                return this.globalQueueNumberField;
            }
            set
            {
                this.globalQueueNumberField = value;
            }
        }

        /// <remarks/>
        public string RoomQueueNumber
        {
            get
            {
                return this.roomQueueNumberField;
            }
            set
            {
                this.roomQueueNumberField = value;
            }
        }

        /// <remarks/>
        public string ExamRoomID
        {
            get
            {
                return this.examRoomIDField;
            }
            set
            {
                this.examRoomIDField = value;
            }
        }

        /// <remarks/>
        public string ExamRoom
        {
            get
            {
                return this.examRoomField;
            }
            set
            {
                this.examRoomField = value;
            }
        }

        /// <remarks/>
        public string GlobalAmountOfUnfinished
        {
            get
            {
                return this.globalAmountOfUnfinishedField;
            }
            set
            {
                this.globalAmountOfUnfinishedField = value;
            }
        }

        /// <remarks/>
        public string RoomAmountOfUnfinished
        {
            get
            {
                return this.roomAmountOfUnfinishedField;
            }
            set
            {
                this.roomAmountOfUnfinishedField = value;
            }
        }

        /// <remarks/>
        public System.DateTime PlannedExamDateTimeInQueue
        {
            get
            {
                return this.plannedExamDateTimeInQueueField;
            }
            set
            {
                this.plannedExamDateTimeInQueueField = value;
            }
        }

        /// <remarks/>
        public string Note
        {
            get
            {
                return this.noteField;
            }
            set
            {
                this.noteField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://HISConService")]
    public partial class ReturnModel
    {

        private string systemIDField;

        private short calledResultField;

        private string resultDescriptionField;

        private string resultBodyFormatField;

        private string resultBodyVersionField;

        private string resultBodyField;

        private string nextActionURIField;

        /// <remarks/>
        public string SystemID
        {
            get
            {
                return this.systemIDField;
            }
            set
            {
                this.systemIDField = value;
            }
        }

        /// <remarks/>
        public short CalledResult
        {
            get
            {
                return this.calledResultField;
            }
            set
            {
                this.calledResultField = value;
            }
        }

        /// <remarks/>
        public string ResultDescription
        {
            get
            {
                return this.resultDescriptionField;
            }
            set
            {
                this.resultDescriptionField = value;
            }
        }

        /// <remarks/>
        public string ResultBodyFormat
        {
            get
            {
                return this.resultBodyFormatField;
            }
            set
            {
                this.resultBodyFormatField = value;
            }
        }

        /// <remarks/>
        public string ResultBodyVersion
        {
            get
            {
                return this.resultBodyVersionField;
            }
            set
            {
                this.resultBodyVersionField = value;
            }
        }

        /// <remarks/>
        public string ResultBody
        {
            get
            {
                return this.resultBodyField;
            }
            set
            {
                this.resultBodyField = value;
            }
        }

        /// <remarks/>
        public string NextActionURI
        {
            get
            {
                return this.nextActionURIField;
            }
            set
            {
                this.nextActionURIField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getModelsInfoCompletedEventHandler(object sender, getModelsInfoCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getModelsInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal getModelsInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public ModelsInfo Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((ModelsInfo)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void DoCommandCompletedEventHandler(object sender, DoCommandCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DoCommandCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal DoCommandCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public ReturnModel sReturnInfo
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((ReturnModel)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591