//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1873
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HYS.MessageDevices.SOAPAdapter.Test.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.carestreamhealth.com/", ConfigurationName="ServiceReference1.PIXServiceSoap")]
    public interface PIXServiceSoap {
        
        // CODEGEN: Generating message contract since element name RequestMessage from namespace http://www.carestreamhealth.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.carestreamhealth.com/MessageCom", ReplyAction="*")]
        HYS.MessageDevices.SOAPAdapter.Test.ServiceReference1.MessageComResponse MessageCom(HYS.MessageDevices.SOAPAdapter.Test.ServiceReference1.MessageComRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MessageComRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MessageCom", Namespace="http://www.carestreamhealth.com/", Order=0)]
        public HYS.MessageDevices.SOAPAdapter.Test.ServiceReference1.MessageComRequestBody Body;
        
        public MessageComRequest() {
        }
        
        public MessageComRequest(HYS.MessageDevices.SOAPAdapter.Test.ServiceReference1.MessageComRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.carestreamhealth.com/")]
    public partial class MessageComRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RequestMessage;
        
        public MessageComRequestBody() {
        }
        
        public MessageComRequestBody(string RequestMessage) {
            this.RequestMessage = RequestMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MessageComResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MessageComResponse", Namespace="http://www.carestreamhealth.com/", Order=0)]
        public HYS.MessageDevices.SOAPAdapter.Test.ServiceReference1.MessageComResponseBody Body;
        
        public MessageComResponse() {
        }
        
        public MessageComResponse(HYS.MessageDevices.SOAPAdapter.Test.ServiceReference1.MessageComResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.carestreamhealth.com/")]
    public partial class MessageComResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int MessageComResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ReturnMessage;
        
        public MessageComResponseBody() {
        }
        
        public MessageComResponseBody(int MessageComResult, string ReturnMessage) {
            this.MessageComResult = MessageComResult;
            this.ReturnMessage = ReturnMessage;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface PIXServiceSoapChannel : HYS.MessageDevices.SOAPAdapter.Test.ServiceReference1.PIXServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class PIXServiceSoapClient : System.ServiceModel.ClientBase<HYS.MessageDevices.SOAPAdapter.Test.ServiceReference1.PIXServiceSoap>, HYS.MessageDevices.SOAPAdapter.Test.ServiceReference1.PIXServiceSoap {
        
        public PIXServiceSoapClient() {
        }
        
        public PIXServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PIXServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PIXServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PIXServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HYS.MessageDevices.SOAPAdapter.Test.ServiceReference1.MessageComResponse HYS.MessageDevices.SOAPAdapter.Test.ServiceReference1.PIXServiceSoap.MessageCom(HYS.MessageDevices.SOAPAdapter.Test.ServiceReference1.MessageComRequest request) {
            return base.Channel.MessageCom(request);
        }
        
        public int MessageCom(string RequestMessage, out string ReturnMessage) {
            HYS.MessageDevices.SOAPAdapter.Test.ServiceReference1.MessageComRequest inValue = new HYS.MessageDevices.SOAPAdapter.Test.ServiceReference1.MessageComRequest();
            inValue.Body = new HYS.MessageDevices.SOAPAdapter.Test.ServiceReference1.MessageComRequestBody();
            inValue.Body.RequestMessage = RequestMessage;
            HYS.MessageDevices.SOAPAdapter.Test.ServiceReference1.MessageComResponse retVal = ((HYS.MessageDevices.SOAPAdapter.Test.ServiceReference1.PIXServiceSoap)(this)).MessageCom(inValue);
            ReturnMessage = retVal.Body.ReturnMessage;
            return retVal.Body.MessageComResult;
        }
    }
}
